### ISSUE TITLE
白名单模式似乎不能用

### ISSUE THREAD

**Issue by BenzLeung** [AXEVO/Clash-MIX#1]
终于找到大佬啦！

昨天从tg看到了3.0 beta1，我马上更新使用了。

但是好像tproxy代理有问题。具体有这些现象：

1.我安装后马上改成了白名单模式，whitelist。其他配置都保持默认。但是改好后，packages.list名单里的app并没有走代理，名单外的也没有走代理。但是如果app支持配置http代理（例如kiwi浏览器）或sock5（例如NekogramX），配置后能正常走代理。之前的2.0版没有此问题。
我忘记测试默认黑名单模式就换回来2.0版了。

2.我看了run.logs，2.0版会记录端口检测，但是3.0版没有记录端口检测过程。但是有记录我packages.list的包名。

3.保留2.0的基础上直接覆盖安装3.0，提示旧的配置已移动到clash.old，但是安装完重启机器后clash.old却是空的。

4.安装过程有个错误提示，大意好像是/data/tmp/clash.apk没有权限，要手动运行/sdcard/clash.apk，但是看起来不影响模块安装。

我的机器：一加10pro，安卓13。

目前我暂时退回了2.0版，本来想把log贴给你的，但是我退回2.0后log都丢失了。。

**Comment by AXEVO** [comment]
感谢反馈，后续我会重点关注这方面问题，建议尝试全新安装（完全卸载2.0再安装3.0）
最近我比较忙没什么时间弄cfm，如果仍不能解决且2.0版本已无法满足要求，可以先使用这位作者的
https://t.me/wtdnwbzda/903 他有对黑白名单方面进行特殊处理，更新比较勤快，但可能需要自己折腾的部分会比较多
对于我自己来说，一般能靠分流解决就不会使用黑白名单

**Comment by AXEVO** [comment]
> 黑名单似乎不能用。 我完全卸载然后装3.0beta1使用， 因为我常有抖音的评论区、搜题软件、学习通等在国内国外均有业务的软件等等走代理而不是直连导致加载变慢，所以我直接加黑名单。 不知道log是不是，3.0beta1: [output-clash.log](https://github.com/AXEVO/Clash-MIX/files/12615428/output-clash.log) [run.logs.txt](https://github.com/AXEVO/Clash-MIX/files/12615437/run.logs.txt)
> 
> Mix2.0 v1.14.5 (t.me/wocao_esu/83) 似乎也是黑名单失效(这版本我不记得了)
> 
> 建议您开放电报评论区，有些人瞎点的“👍🏻“👎”成了无意义无用反馈或者不知道或者懒得来github提issue



> 终于找到大佬啦！
> 
> 昨天从tg看到了3.0 beta1，我马上更新使用了。
> 
> 但是好像tproxy代理有问题。具体有这些现象：
> 
> 1.我安装后马上改成了白名单模式，whitelist。其他配置都保持默认。但是改好后，packages.list名单里的app并没有走代理，名单外的也没有走代理。但是如果app支持配置http代理（例如kiwi浏览器）或sock5（例如NekogramX），配置后能正常走代理。之前的2.0版没有此问题。 我忘记测试默认黑名单模式就换回来2.0版了。
> 
> 2.我看了run.logs，2.0版会记录端口检测，但是3.0版没有记录端口检测过程。但是有记录我packages.list的包名。
> 
> 3.保留2.0的基础上直接覆盖安装3.0，提示旧的配置已移动到clash.old，但是安装完重启机器后clash.old却是空的。
> 
> 4.安装过程有个错误提示，大意好像是/data/tmp/clash.apk没有权限，要手动运行/sdcard/clash.apk，但是看起来不影响模块安装。
> 
> 我的机器：一加10pro，安卓13。
> 
> 目前我暂时退回了2.0版，本来想把log贴给你的，但是我退回2.0后log都丢失了。。

目前clash mix 3.0的养老版已经能正常使用黑名单，欢迎体验
