### ISSUE TITLE
请问为什么更新失败了？

### ISSUE THREAD

**Issue by dcvh556tfg** [AXEVO/Clash-MIX#2]
![Screenshot_2024-03-27-12-11-23-704_me weishu kernelsu](https://github.com/AXEVO/Clash-MIX/assets/90571500/415c86f3-9781-4ccb-b76b-f0c76c19ed41)
![Screenshot_2024-03-27-12-11-23-704_me weishu kernelsu](https://github.com/AXEVO/Clash-MIX/assets/90571500/a2c9f0b5-5a96-4660-a2b3-37dadfc2fe95)
![Screenshot_2024-03-27-12-09-16-897_bin mt plus](https://github.com/AXEVO/Clash-MIX/assets/90571500/cefef017-84e2-4d7e-80d0-1fd099d12230)
更新失败应该怎么更新？没看到tg频道，作者名字也搜不到

**Comment by AXEVO** [comment]
为了安全起见加了一点小门槛，那个更新就是提示，需要自己打包，方法很简单，下载最新存储库内容 https://github.com/AXEVO/Clash-MIX/archive/refs/heads/Clash-MIX-3.0.zip
解压缩，将解压出来的一堆文件和文件夹重新压缩打包 然后刷入即可
